version: 3

project:
  id: github.com/splunk/splunk-connect-for-syslog
  name: splunk-connect-for-syslog
  team: gdi
  link: splunk.github.io/splunk-connect-for-syslog
  url: github.com/splunk/splunk-connect-for-syslog
